##  Binary Classification using Perception, MLP and Autoencoder

#### Loading the required libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, auc

from keras.models import Sequential, Model
from keras.layers import Dense, Input
from keras.layers.normalization import BatchNormalization
from keras.utils import to_categorical

import matplotlib.pyplot as plt

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


#### Problem

    Is to identify products at risk of backorder before the event occurs so the business has time to react. 

#### Data

Data file contains the historical data for the 8 weeks prior to the week we are trying to predict. The data was taken as weekly snapshots at the start of each week. Columns are defined as follows:

    sku - Random ID for the product

    national_inv - Current inventory level for the part

    lead_time - Transit time for product (if available)

    in_transit_qty - Amount of product in transit from source

    forecast_3_month - Forecast sales for the next 3 months

    forecast_6_month - Forecast sales for the next 6 months

    forecast_9_month - Forecast sales for the next 9 months

    sales_1_month - Sales quantity for the prior 1 month time period

    sales_3_month - Sales quantity for the prior 3 month time period

    sales_6_month - Sales quantity for the prior 6 month time period

    sales_9_month - Sales quantity for the prior 9 month time period

    min_bank - Minimum recommend amount to stock

    potential_issue - Source issue for part identified

    pieces_past_due - Parts overdue from source

    perf_6_month_avg - Source performance for prior 6 month period

    perf_12_month_avg - Source performance for prior 12 month period

    local_bo_qty - Amount of stock orders overdue

    deck_risk - Part risk flag

    oe_constraint - Part risk flag

    ppap_risk - Part risk flag

    stop_auto_buy - Part risk flag

    rev_stop - Part risk flag

    went_on_backorder - Product actually went on backorder. This is the target value.

#### Identify Right Error Metrics

    Based on the businees have to identify right error metrics.

#### Loading the data

In [2]:
data = pd.read_csv("BackOrders.csv", header=0)

#### Understand the Data

See the No. row and columns

In [3]:
data.shape

(61589, 23)

Display the columns

In [4]:
data.columns

Index(['sku', 'national_inv', 'lead_time', 'in_transit_qty',
       'forecast_3_month', 'forecast_6_month', 'forecast_9_month',
       'sales_1_month', 'sales_3_month', 'sales_6_month', 'sales_9_month',
       'min_bank', 'potential_issue', 'pieces_past_due', 'perf_6_month_avg',
       'perf_12_month_avg', 'local_bo_qty', 'deck_risk', 'oe_constraint',
       'ppap_risk', 'stop_auto_buy', 'rev_stop', 'went_on_backorder'],
      dtype='object')

Display the index

In [5]:
data.index

RangeIndex(start=0, stop=61589, step=1)

See the top rows of the data

In [6]:
data[:3]

sku  national_inv  lead_time  in_transit_qty  forecast_3_month  \
0  1888279           117        NaN               0                 0   
1  1870557             7        2.0               0                 0   
2  1475481           258       15.0              10                10   

   forecast_6_month  forecast_9_month  sales_1_month  sales_3_month  \
0                 0                 0              0              0   
1                 0                 0              0              0   
2                77               184             46            132   

   sales_6_month        ...         pieces_past_due  perf_6_month_avg  \
0             15        ...                       0            -99.00   
1              0        ...                       0              0.50   
2            256        ...                       0              0.54   

  perf_12_month_avg  local_bo_qty  deck_risk  oe_constraint  ppap_risk  \
0            -99.00             0         No             No        Yes   
1              0.28             0        Yes             No         No   
2              0.70             0         No             No         No   

  stop_auto_buy rev_stop went_on_backorder  
0           Yes       No                No  
1           Yes       No                No  
2           Yes       No                No  

[3 rows x 23 columns]

Shows a quick statistic summary of your data using describe

In [7]:
data.describe(include='all')

sku   national_inv     lead_time  in_transit_qty  \
count   6.158900e+04   61589.000000  58186.000000    61589.000000   
unique           NaN            NaN           NaN             NaN   
top              NaN            NaN           NaN             NaN   
freq             NaN            NaN           NaN             NaN   
mean    2.037188e+06     287.721882      7.559619       30.192843   
std     6.564178e+05    4233.906931      6.498952      792.869253   
min     1.068628e+06   -2999.000000      0.000000        0.000000   
25%     1.498574e+06       3.000000      4.000000        0.000000   
50%     1.898033e+06      10.000000      8.000000        0.000000   
75%     2.314826e+06      57.000000      8.000000        0.000000   
max     3.284895e+06  673445.000000     52.000000   170976.000000   

        forecast_3_month  forecast_6_month  forecast_9_month  sales_1_month  \
count       6.158900e+04      6.158900e+04      6.158900e+04   61589.000000   
unique               NaN               NaN               NaN            NaN   
top                  NaN               NaN               NaN            NaN   
freq                 NaN               NaN               NaN            NaN   
mean        1.692728e+02      3.150413e+02      4.535760e+02      44.742957   
std         5.286742e+03      9.774362e+03      1.420201e+04    1373.805831   
min         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
25%         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
50%         0.000000e+00      0.000000e+00      0.000000e+00       0.000000   
75%         1.200000e+01      2.500000e+01      3.600000e+01       6.000000   
max         1.126656e+06      2.094336e+06      3.062016e+06  295197.000000   

        sales_3_month  sales_6_month        ...         pieces_past_due  \
count    61589.000000   6.158900e+04        ...            61589.000000   
unique            NaN            NaN        ...                     NaN   
top               NaN            NaN        ...                     NaN   
freq              NaN            NaN        ...                     NaN   
mean       150.732631   2.835465e+02        ...                1.605400   
std       5224.959649   8.872270e+03        ...               42.309229   
min          0.000000   0.000000e+00        ...                0.000000   
25%          0.000000   0.000000e+00        ...                0.000000   
50%          2.000000   4.000000e+00        ...                0.000000   
75%         17.000000   3.400000e+01        ...                0.000000   
max     934593.000000   1.799099e+06        ...             7392.000000   

        perf_6_month_avg perf_12_month_avg  local_bo_qty  deck_risk  \
count       61589.000000      61589.000000  61589.000000      61589   
unique               NaN               NaN           NaN          2   
top                  NaN               NaN           NaN         No   
freq                 NaN               NaN           NaN      48145   
mean           -6.264182         -5.863664      1.205361        NaN   
std            25.537906         24.844514     29.981155        NaN   
min           -99.000000        -99.000000      0.000000        NaN   
25%             0.620000          0.640000      0.000000        NaN   
50%             0.820000          0.800000      0.000000        NaN   
75%             0.960000          0.950000      0.000000        NaN   
max             1.000000          1.000000   2999.000000        NaN   

        oe_constraint  ppap_risk stop_auto_buy rev_stop went_on_backorder  
count           61589      61589         61589    61589             61589  
unique              2          2             2        2                 2  
top                No         No           Yes       No                No  
freq            61577      53792         59303    61569             50296  
mean              NaN        NaN           NaN      NaN               NaN  
std               NaN        

Display data type of each variable

In [8]:
data.dtypes

sku                    int64
national_inv           int64
lead_time            float64
in_transit_qty         int64
forecast_3_month       int64
forecast_6_month       int64
forecast_9_month       int64
sales_1_month          int64
sales_3_month          int64
sales_6_month          int64
sales_9_month          int64
min_bank               int64
potential_issue       object
pieces_past_due        int64
perf_6_month_avg     float64
perf_12_month_avg    float64
local_bo_qty           int64
deck_risk             object
oe_constraint         object
ppap_risk             object
stop_auto_buy         object
rev_stop              object
went_on_backorder     object
dtype: object

#### Observations

    sku is Categorical but is interpreted as int64 
    potential_issue, deck_risk, oe_constraint, ppap_risk, stop_auto_buy, rev_stop, and went_on_backorder are also categorical but is interpreted as object. 

#### Convert all the attributes to appropriate type

Data type conversion

    Using astype('category') to convert potential_issue, deck_risk, oe_constraint, ppap_risk, stop_auto_buy, rev_stop, and went_on_backorder attributes to categorical attributes.


In [9]:
for col in ['sku', 'potential_issue', 'deck_risk', 'oe_constraint', 'ppap_risk', 'stop_auto_buy', 'rev_stop', 'went_on_backorder']:
    data[col] = data[col].astype('category')

Display data type of each variable

In [10]:
data.dtypes

sku                  category
national_inv            int64
lead_time             float64
in_transit_qty          int64
forecast_3_month        int64
forecast_6_month        int64
forecast_9_month        int64
sales_1_month           int64
sales_3_month           int64
sales_6_month           int64
sales_9_month           int64
min_bank                int64
potential_issue      category
pieces_past_due         int64
perf_6_month_avg      float64
perf_12_month_avg     float64
local_bo_qty            int64
deck_risk            category
oe_constraint        category
ppap_risk            category
stop_auto_buy        category
rev_stop             category
went_on_backorder    category
dtype: object

#### Delete sku attribute

In [11]:
np.size(np.unique(data.sku, return_counts=True)[0])

61589

In [12]:
data.drop('sku', axis=1, inplace=True)

#### Missing Data

    Missing value analysis and dropping the records with missing values

In [13]:
data.isnull().sum()

national_inv            0
lead_time            3403
in_transit_qty          0
forecast_3_month        0
forecast_6_month        0
forecast_9_month        0
sales_1_month           0
sales_3_month           0
sales_6_month           0
sales_9_month           0
min_bank                0
potential_issue         0
pieces_past_due         0
perf_6_month_avg        0
perf_12_month_avg       0
local_bo_qty            0
deck_risk               0
oe_constraint           0
ppap_risk               0
stop_auto_buy           0
rev_stop                0
went_on_backorder       0
dtype: int64

Observing the number of records before and after missing value records removal

In [14]:
print (data.shape)

(61589, 22)


In [15]:
#Since the number of missing values is about 5%. For initial analysis we ignore all these records
data = data.dropna(axis=0)

In [16]:
data.isnull().sum()
print(data.shape)

(58186, 22)


#### Converting Categorical to Numeric

For some of the models all the independent attribute should be of type numeric and Linear Regression model is one among them.
But this data set has some categorial attributes.

'pandas.get_dummies' To convert convert categorical variable into dummy/indicator variables


In [17]:
print (data.columns)

Index(['national_inv', 'lead_time', 'in_transit_qty', 'forecast_3_month',
       'forecast_6_month', 'forecast_9_month', 'sales_1_month',
       'sales_3_month', 'sales_6_month', 'sales_9_month', 'min_bank',
       'potential_issue', 'pieces_past_due', 'perf_6_month_avg',
       'perf_12_month_avg', 'local_bo_qty', 'deck_risk', 'oe_constraint',
       'ppap_risk', 'stop_auto_buy', 'rev_stop', 'went_on_backorder'],
      dtype='object')


Creating dummy variables.

    If we have k levels in a category, then we create k-1 dummy variables as the last one would be redundant. So we use the parameter drop_first in pd.get_dummies function that drops the first level in each of the category


In [18]:
categorical_Attributes = data.select_dtypes(include=['category']).columns

In [19]:
data = pd.get_dummies(columns=categorical_Attributes, data=data, prefix=categorical_Attributes, prefix_sep="_",drop_first=True)

In [20]:
print (data.columns, data.shape)

Index(['national_inv', 'lead_time', 'in_transit_qty', 'forecast_3_month',
       'forecast_6_month', 'forecast_9_month', 'sales_1_month',
       'sales_3_month', 'sales_6_month', 'sales_9_month', 'min_bank',
       'pieces_past_due', 'perf_6_month_avg', 'perf_12_month_avg',
       'local_bo_qty', 'potential_issue_Yes', 'deck_risk_Yes',
       'oe_constraint_Yes', 'ppap_risk_Yes', 'stop_auto_buy_Yes',
       'rev_stop_Yes', 'went_on_backorder_Yes'],
      dtype='object') (58186, 22)


#### Target attribute distribution

In [21]:
pd.value_counts(data['went_on_backorder_Yes'].values)

0    47217
1    10969
dtype: int64

#### Split the data in to train and test

sklearn.model_selection.train_test_split

    Split arrays or matrices into random train and test subsets

In [22]:
#Performing train test split on the data
X, y = data.loc[:,data.columns!='went_on_backorder_Yes'].values, data.loc[:,'went_on_backorder_Yes'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)


In [23]:
#To get the distribution in the target in train and test
print(pd.value_counts(y_train))
print(pd.value_counts(y_test))

0    33067
1     7663
dtype: int64
0    14150
1     3306
dtype: int64


#### Perceptron Model Building

In [24]:
perceptron_model = Sequential()

perceptron_model.add(Dense(1, input_dim=X_train.shape[1], activation='sigmoid', kernel_initializer='normal'))

In [25]:
perceptron_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [26]:
perceptron_model.fit(X_train, y_train, epochs=30, batch_size=64)

Epoch 1/30
40730/40730 [==============================] - 1s 23us/step - loss: 0.6477 - acc: 0.8114
Epoch 2/30
40730/40730 [==============================] - 1s 16us/step - loss: 0.4612 - acc: 0.8416
Epoch 3/30
40730/40730 [==============================] - 1s 24us/step - loss: 0.4941 - acc: 0.8506
Epoch 4/30
40730/40730 [==============================] - 1s 26us/step - loss: 0.4470 - acc: 0.8564
Epoch 5/30
40730/40730 [==============================] - 1s 24us/step - loss: 0.4486 - acc: 0.8610
Epoch 6/30
40730/40730 [==============================] - 1s 29us/step - loss: 0.4236 - acc: 0.8642
Epoch 7/30
40730/40730 [==============================] - 1s 26us/step - loss: 0.4193 - acc: 0.8635
Epoch 8/30
40730/40730 [==============================] - 1s 17us/step - loss: 0.4173 - acc: 0.8648
Epoch 9/30
40730/40730 [==============================] - 1s 16us/step - loss: 0.4306 - acc: 0.8631
Epoch 10/30
40730/40730 [==============================] - 1s 17us/step - loss: 0.4120 - acc: 0.8666

#### Predictions

In [27]:
test_pred=perceptron_model.predict_classes(X_test)
train_pred=perceptron_model.predict_classes(X_train)

40730/40730 [==============================] - 0s 10us/step


#### Getting evaluation metrics and evaluating model performance

In [28]:
confusion_matrix_test = confusion_matrix(y_test, test_pred)
confusion_matrix_train = confusion_matrix(y_train, train_pred)

print(confusion_matrix_train)
print(confusion_matrix_test)

[[31372  1695]
 [ 6567  1096]]
[[13414   736]
 [ 2850   456]]


#### Calculate Accuracy, True Positive Rate and True Negative Rates

In [29]:
Accuracy_Train = (confusion_matrix_train[0,0]+confusion_matrix_train[1,1])/(confusion_matrix_train[0,0]+confusion_matrix_train[0,1]+confusion_matrix_train[1,0]+confusion_matrix_train[1,1])
TNR_Train = confusion_matrix_train[0,0]/(confusion_matrix_train[0,0]+confusion_matrix_train[0,1])
TPR_Train = confusion_matrix_train[1,1]/(confusion_matrix_train[1,0]+confusion_matrix_train[1,1])

print("Train TNR: ",TNR_Train)
print("Train TPR: ",TPR_Train)
print("Train Accuracy: ",Accuracy_Train)

Train TNR:  0.9487404360843137
Train TPR:  0.14302492496411326
Train Accuracy:  0.7971519764301498


In [30]:
Accuracy_Test = (confusion_matrix_test[0,0]+confusion_matrix_test[1,1])/(confusion_matrix_test[0,0]+confusion_matrix_test[0,1]+confusion_matrix_test[1,0]+confusion_matrix_test[1,1])
TNR_Test = confusion_matrix_test[0,0]/(confusion_matrix_test[0,0] +confusion_matrix_test[0,1])
TPR_Test = confusion_matrix_test[1,1]/(confusion_matrix_test[1,0] +confusion_matrix_test[1,1])

print("Test TNR: ",TNR_Test)
print("Test TPR: ",TPR_Test)
print("Test Accuracy: ",Accuracy_Test)

Test TNR:  0.9479858657243816
Test TPR:  0.13793103448275862
Test Accuracy:  0.7945692025664528


#### MLP Model Building

In [31]:
mlp_model = Sequential()

mlp_model.add(Dense(12, input_dim=X_train.shape[1], activation='relu', kernel_initializer='glorot_normal'))
mlp_model.add(Dense(8, activation='relu', kernel_initializer='normal'))
mlp_model.add(Dense(1, activation='sigmoid', kernel_initializer='normal'))

In [32]:
mlp_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [33]:
mlp_model.fit(X_train, y_train, epochs=30, batch_size=64)

Epoch 1/30
40730/40730 [==============================] - 1s 25us/step - loss: 0.4113 - acc: 0.8174
Epoch 2/30
40730/40730 [==============================] - 1s 18us/step - loss: 0.3013 - acc: 0.8657
Epoch 3/30
40730/40730 [==============================] - 1s 18us/step - loss: 0.2888 - acc: 0.8881
Epoch 4/30
40730/40730 [==============================] - 1s 17us/step - loss: 0.2792 - acc: 0.8888
Epoch 5/30
40730/40730 [==============================] - 1s 17us/step - loss: 0.2703 - acc: 0.8902
Epoch 6/30
40730/40730 [==============================] - 1s 17us/step - loss: 0.2652 - acc: 0.8932: 0s - loss: 0.2603 - acc: 0.
Epoch 7/30
40730/40730 [==============================] - 1s 17us/step - loss: 0.2620 - acc: 0.8939
Epoch 8/30
40730/40730 [==============================] - 1s 18us/step - loss: 0.2580 - acc: 0.8954
Epoch 9/30
40730/40730 [==============================] - 1s 18us/step - loss: 0.2549 - acc: 0.8979
Epoch 10/30
40730/40730 [==============================] - 1s 18us/step

#### Predictions

In [34]:
test_pred=mlp_model.predict_classes(X_test)
train_pred=mlp_model.predict_classes(X_train)

40730/40730 [==============================] - ETA:  - 1s 13us/step


#### Getting evaluation metrics and evaluating model performance

In [35]:
confusion_matrix_test = confusion_matrix(y_test, test_pred)
confusion_matrix_train = confusion_matrix(y_train, train_pred)

print(confusion_matrix_train)
print(confusion_matrix_test)

[[31038  2029]
 [ 1867  5796]]
[[13286   864]
 [  814  2492]]


#### Calculate Accuracy, True Positive Rate and True Negative Rates

In [36]:
Accuracy_Train=(confusion_matrix_train[0,0]+confusion_matrix_train[1,1])/(confusion_matrix_train[0,0]+confusion_matrix_train[0,1]+confusion_matrix_train[1,0]+confusion_matrix_train[1,1])
TNR_Train= confusion_matrix_train[0,0]/(confusion_matrix_train[0,0]+confusion_matrix_train[0,1])
TPR_Train= confusion_matrix_train[1,1]/(confusion_matrix_train[1,0]+confusion_matrix_train[1,1])

print("Train TNR: ",TNR_Train)
print("Train TPR: ",TPR_Train)
print("Train Accuracy: ",Accuracy_Train)

Train TNR:  0.93863973145432
Train TPR:  0.7563617382226282
Train Accuracy:  0.9043456911367542


In [37]:
Accuracy_Test=(confusion_matrix_test[0,0]+confusion_matrix_test[1,1])/(confusion_matrix_test[0,0]+confusion_matrix_test[0,1]+confusion_matrix_test[1,0]+confusion_matrix_test[1,1])
TNR_Test= confusion_matrix_test[0,0]/(confusion_matrix_test[0,0] +confusion_matrix_test[0,1])
TPR_Test= confusion_matrix_test[1,1]/(confusion_matrix_test[1,0] +confusion_matrix_test[1,1])

print("Test TNR: ",TNR_Test)
print("Test TPR: ",TPR_Test)
print("Test Accuracy: ",Accuracy_Test)

Test TNR:  0.9389399293286219
Test TPR:  0.7537810042347247
Test Accuracy:  0.9038725939505041


#### Perceptron Model Building with both actual and non-linear features

In [48]:
perceptron_model = Sequential()

perceptron_model.add(Dense(1, input_dim=X_train.shape[1], activation='sigmoid', kernel_initializer='normal'))

In [49]:
perceptron_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [50]:
perceptron_model.fit(X_train, y_train, epochs=30, batch_size=64)

Epoch 1/30
40730/40730 [==============================] - 1s 22us/step - loss: 0.7750 - acc: 0.8331
Epoch 2/30
40730/40730 [==============================] - 1s 15us/step - loss: 0.4569 - acc: 0.8840
Epoch 3/30
40730/40730 [==============================] - 1s 16us/step - loss: 0.4326 - acc: 0.8856
Epoch 4/30
40730/40730 [==============================] - 1s 16us/step - loss: 0.4033 - acc: 0.8895: 0s - loss: 0.3830 - acc
Epoch 5/30
40730/40730 [==============================] - 1s 16us/step - loss: 0.4355 - acc: 0.8845
Epoch 6/30
40730/40730 [==============================] - 1s 16us/step - loss: 0.4216 - acc: 0.8872
Epoch 7/30
40730/40730 [==============================] - 1s 15us/step - loss: 0.3971 - acc: 0.8902
Epoch 8/30
40730/40730 [==============================] - 1s 15us/step - loss: 0.4282 - acc: 0.8853
Epoch 9/30
40730/40730 [==============================] - 1s 15us/step - loss: 0.3985 - acc: 0.8912
Epoch 10/30
40730/40730 [==============================] - 1s 16us/step - l

#### Predictions

In [51]:
test_pred=perceptron_model.predict_classes(X_test)
train_pred=perceptron_model.predict_classes(X_train)

40730/40730 [==============================] - 0s 11us/step


#### Getting evaluation metrics and evaluating model performance

In [52]:
confusion_matrix_test = confusion_matrix(y_test, test_pred)
confusion_matrix_train = confusion_matrix(y_train, train_pred)

print(confusion_matrix_train)
print(confusion_matrix_test)

[[31116  1951]
 [ 2249  5414]]
[[13311   839]
 [  974  2332]]


#### Calculate Accuracy, True Positive Rate and True Negative Rates

In [53]:
Accuracy_Train=(confusion_matrix_train[0,0]+confusion_matrix_train[1,1])/(confusion_matrix_train[0,0]+confusion_matrix_train[0,1]+confusion_matrix_train[1,0]+confusion_matrix_train[1,1])
TNR_Train= confusion_matrix_train[0,0]/(confusion_matrix_train[0,0]+confusion_matrix_train[0,1])
TPR_Train= confusion_matrix_train[1,1]/(confusion_matrix_train[1,0]+confusion_matrix_train[1,1])

print("Train TNR: ",TNR_Train)
print("Train TPR: ",TPR_Train)
print("Train Accuracy: ",Accuracy_Train)

Train TNR:  0.9409985786433605
Train TPR:  0.7065118099960851
Train Accuracy:  0.8968819052295606


In [54]:
Accuracy_Test=(confusion_matrix_test[0,0]+confusion_matrix_test[1,1])/(confusion_matrix_test[0,0]+confusion_matrix_test[0,1]+confusion_matrix_test[1,0]+confusion_matrix_test[1,1])
TNR_Test= confusion_matrix_test[0,0]/(confusion_matrix_test[0,0] +confusion_matrix_test[0,1])
TPR_Test= confusion_matrix_test[1,1]/(confusion_matrix_test[1,0] +confusion_matrix_test[1,1])

print("Test TNR: ",TNR_Test)
print("Test TPR: ",TPR_Test)
print("Test Accuracy: ",Accuracy_Test)

Test TNR:  0.9407067137809187
Test TPR:  0.705384150030248
Test Accuracy:  0.8961388634280477
